### ISSUE TITLE
Update StudentList logic

### ISSUE THREAD

**Issue by lucianosimoni** [boolean-uk/team-dev-frontend-client#213]
# Reason
Because if the `teacher` presses a _cohort_ item (In the _CohortsList_ component), it would take the `teacher` to `/cohorts/:cohortId`.

And the _StudentList_ only renders the url _/cohorts/:cohortId_ based on the _user_ prop that it receives. And the `Teacher` does not have a user.cohortId, cause the button was pressed (So the _url_ is dynamic).

# Solution
Inside the `useEffect`. add the following condition to the first `client.get`:
- `If student`: get the _cohort_ based on the `user.cohortId`
- (else) `if teacher`: get the _cohort_ based on the `urlParams.id`
> console.log the urlParams to see the key name.

# Todo
- [ ] Add _useParams_ to StudentList.
- [ ] create a condition to check if user is either Student or Teacher.
- [ ] Remove const _cohortId_ because it will not be as readable as _user.cohortId_. (Replace basically)
- [ ] Update the function `updateStudentsList` from issue #120 

# Wait for issue #120 to be merged, then update respectively - Look at lest todo

**Comment by OlhaDorofiychuk** [comment]
sounds good

**Comment by dogezen** [comment]
good one
